name: 'Install cargo-prebuilt'
description: 'Install cargo prebuilt and crates to a runner'
author: 'harmless-tech, cargo-prebuilt'
branding:
  icon: arrow-down-circle
  color: gray-dark

inputs:
  prebuilt-version:
    required: true
    description: 'Version of cargo-prebuilt to use'
    default: latest
  prebuilt-target:
    required: true
    description: 'Target for the version of cargo-prebuilt to install'
    default: current
  prebuilt-verify:
    required: true
    description: 'Verify downloaded cargo prebuilt'
    default: 'sha256'
  pkgs:
    description:
      'A CSV list of prebuilt crates needed with optional version numbers (see
      cargo-prebuilt cli)'
    default: ''

  target:
    description: 'Target for the version of the tools to install'
    default: ''
  safe:
    description: 'Do not overwrite binaries that already exist'
    default: ''
  update:
    description: 'Update packages based on binary hash'
    default: ''
  index:
    description: 'Index to use'
    default: ''
  pub-key:
    description:
      'A public verifying key encoded as base64. (Or a list of them using CSV).'
    default: ''
  auth:
    description: 'Auth token to use for private indexes'
    default: ''
  index-key:
    description: 'Index to use, pulling from config file'
    default: ''
  ci:
    description:
      'Do not download reports, check for a config file, and ignore safe mode'
    default: 'true'
  no-sig:
    description: 'Do not verify downloaded info.jsons and hashes.jsons'
    default: ''
  no-hash:
    description: 'Do not verify downloaded archives'
    default: ''
  hash-bins:
    description: 'Hash and verify extracted binaries'
    default: ''
  path:
    description:
      'Path to the folder where downloaded binaries will be installed. (Default:
      $CARGO_HOME/bin)'
    default: ''
  report-path:
    description:
      'Path to the folder where the reports will be put (Default: See
      https://github.com/cargo-prebuilt/cargo-prebuilt/blob/main/docs/PATHS.md#reports)'
    default: ''
  no-create-path:
    description: 'Do not create the report and/or bin folder if it is missing'
    default: ''
  reports:
    description:
      'Reports to be downloaded in a CSV format (Default: license) (See: See
      https://github.com/cargo-prebuilt/cargo-prebuilt/blob/main/docs/REPORT_TYPES.md)'
    default: ''
  config:
    description:
      'Path to the config file (Default: See
      https://github.com/cargo-prebuilt/cargo-prebuilt/blob/main/docs/PATHS.md#config)'
    default: ''
  require-config:
    description: 'Require a config file to be used. (--ci will override this)'
    default: ''
  out:
    description: 'Output events'
    default: 'true'
  get-latest:
    description: 'Get latest versions of crates in index and then exit'
    default: ''
  color:
    description: 'Force color to be turned on or off'
    default: 'true'

outputs:
  prebuilt-version:
    description: 'Cargo prebuilt version that was installed'
  prebuilt-target:
    description: 'Cargo prebuilt target that was installed'
  prebuilt-binary:
    description: 'Cargo prebuilt binary install location'
  out:
    description: 'Stdout of cargo-prebuilt if it downloaded any tools'

runs:
  using: 'node24'
  main: 'dist/index.js'
