name: 'Install cargo-prebuilt'
description: 'Install cargo prebuilt and crates to a runner'
author: 'harmless-tech, cargo-prebuilt'
branding:
  icon: arrow-down-circle
  color: gray-dark
inputs:
  prebuilt-version:
    required: true
    description: 'Version of cargo-prebuilt to use'
    default: latest
  prebuilt-target:
    required: true
    description: 'Target for the version of cargo-prebuilt to install'
    default: current
  prebuilt-verify:
    required: true
    description: 'Verify downloaded cargo prebuilt'
    default: 'sha256'
  pkgs:
    description: 'A CSV list of prebuilt crates needed with optional version numbers (see cargo-prebuilt cli)'
    default: ''
  target:
    description: 'Target for the version of the tools to install'
    default: ''
  index-key:
    description: 'Index to use from the config file. Requires ci to be set to false if using'
    default: ''
  index:
    description: 'Index to use to install tools from'
    default: ''
  auth:
    description: 'Auth token for index if needed'
    default: ''
  config:
    description: 'Path to config file to use. Requires ci to be set to false if using'
    default: ''
  path:
    description: 'Path where prebuilt crates are installed'
    default: ''
  report-path:
    description: 'Path where reports are installed'
    default: ''
  ci:
    description: 'Use the --ci flag (On by default)'
    default: 'true'
  sig:
    description: 'A public verifying key encoded as base64'
    default: ''
  no-verify:
    description: 'Do not verify downloaded files'
    default: ''
  safe:
    description: 'Do not overwrite existing files'
    default: ''
  out:
    description: 'Print out events (On by default)'
    default: 'true'
  color:
    description: 'Enable or disable color'
    default: ''
outputs:
  prebuilt-version:
    description: 'Cargo prebuilt version that was installed'
  prebuilt-target:
    description: 'Cargo prebuilt target that was installed'
  out:
    description: 'Stdout of cargo-prebuilt if it downloaded any tools'
runs:
  using: 'node16'
  main: 'dist/index.js'
