name: 'Install cargo-prebuilt'
description: 'Install cargo prebuilt to a runner'
author: 'harmless-tech, cargo-prebuilt'
branding:
  icon: arrow-down-circle
  color: gray-dark
inputs:
  version:
    required: true
    description: 'Version of cargo-prebuilt to use'
    default: latest
  target:
    required: true
    description: 'Target for the version of cargo-prebuilt to install'
    default: current
  tools:
    description: 'A CSV list of tools needed with optional version numbers (see cargo-prebuilt cli)'
    default: ''
  tools-target:
    description: 'Target for the version of the tools to install'
    default: current
  tools-index:
    description: 'Index to use to install tools from'
    default: ''
  tools-auth:
    description: 'Auth token for index if needed'
    default: ''
  tools-path:
    description: 'Path where tools are installed'
    default: ''
outputs:
  version:
    description: 'Version that was installed'
  target:
    description: 'Target that was installed'
runs:
  using: 'node16'
  main: 'dist/index.js'
