name: 'Install cargo-prebuilt'
description: 'Install cargo prebuilt to a runner'
author: 'harmless-tech, cargo-prebuilt'
branding:
  icon: arrow-down-circle
  color: gray-dark
inputs:
  version:
    required: true
    description: 'Version of cargo-prebuilt to use'
    default: latest
  target:
    required: true
    description: 'Target for the version of cargo-prebuilt to install'
    default: current
  tools:
    description: 'A CSV list of tools needed with optional version numbers (see cargo-prebuilt cli)'
    default: ''
  tools-target:
    description: 'Target for the version of the tools to install'
    default: current
  always-install:
    description: 'If the current installed version of cargo-prebuilt should be overridden'
    default: 'true'
outputs:
  version:
    description: 'Version that was installed'
  target:
    description: 'Target that was installed'
  tools-installed:
    description: 'A CSV of the tools that were installed (EX: just@1.8.0,rtx-cli@1.22.5)'
runs:
  using: 'node16'
  main: 'dist/index.js'
